### ISSUE TITLE
Add Project.toml

### ISSUE THREAD

**Issue by iblislin** [JuliaML/Reinforce.jl#38]
UUID is here: https://github.com/JuliaRegistries/General/blob/master/R/Reinforce/Package.toml#L2
```
uuid = "0376cc21-f8a9-5fcf-8891-fde1415a4fd3"
```

**Comment by felixchalumeau** [comment]
Hi ! I have had a problem installing Reinforce as one the dependencies, LearnBase, has evolved recently to version 0.4.*, which does not have LearnBase.params anymore. This create an error in the precompiling at line 170 of Reinforce.jl file as the mutable struct MouseActionSet{T} is trying to use DiscreteSet from LearnBase.params.

I managed to use it by adding Project.toml and Manifest.toml by myself and forcing to get LearnBase 0.2.2 instead but it wasn't very convenient. 

Thus, it would be great to have the Project.toml initially and to fix that issue of dependency toward LearnBase. 

Should I also create an issue about the dependency ? 

Thanks !

**Comment by iblislin** [comment]
Ah, I will fix this issue.

**Comment by iblislin** [comment]
@felixchalumeau I created a PR #44, let's upgrade LearnBase.jl

**Comment by felixchalumeau** [comment]
Great ! Thanks !
