### ISSUE TITLE
undefined function in CartPole environment

### ISSUE THREAD

**Issue by felixchalumeau** [JuliaML/Reinforce.jl#45]
Not sure that the function state(env) is defined in line 50 & 70 of the CartPoleEnv module. 
It should probably replaced by env.state ! Am I wrong ? 

Reinforce.jl/src/envs/cartpole.jl

**Comment by iblislin** [comment]
https://github.com/JuliaML/Reinforce.jl#environment-interface
The `state` function is the standard interface of a `AbstractEvnironment`,
so you do not need to replace them.

**Comment by felixchalumeau** [comment]
It raises 
`ERROR: LoadError: UndefVarError: state not defined`

We should then consider adding state in the imports at the beginning of the module:
At this point, we have: 
`import Reinforce: reset!, actions, finished, step!` and we should move to:
`import Reinforce: reset!, actions, finished, step!, state`

**Comment by iblislin** [comment]
Ah, you're right.
Could you send a PR about this issue?

**Comment by felixchalumeau** [comment]
yes !
